### ISSUE TITLE
Permitting team can flag 'Needs RFI'

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1347] opened 2023-03-14 20:20 UTC
As a permitting analyst
I want to flag an application as needing an RFI
So that an RFI is sent out at the right time

**Description:**
The permitting team has requested a functionality to flag an application as needing an RFI when they are conducting their assessment.

# Acceptance Criteria:

## {Page Name}

**Screen**

[wireframe 1]
[wireframe 2]

- [ ] .

**Page Behaviours**

- [ ] .
- [ ] .
- [ ] .

**Validations**

- [ ] .
- [ ] .
- [ ] .

**Actions**

- [ ] .
- [ ] .
- [ ] .

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by elliottSlee** [comment] 2023-03-27 18:34
dupe of #1374

**Closed by elliottSlee** 2023-03-27 18:34 UTC
Labels: User Story, Need Refinement
