### ISSUE TITLE
Implement Authorization feature

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#363] opened 2022-07-29 18:49 UTC
**As a** user 
**I want** to log in as a designated role
**So that** I can have access to specific features in the system

----

## Description
1) Identify a list of users in a designated Role
2) Set Permissions
3) Assign Permissions to one or more Roles

## Acceptance Criteria
- [ ] .

- [ ] .

- [ ] .

**Comment by elliottSlee** [comment] 2022-08-02 21:16
Is this a duplicate of #26 or #29?

**Closed** 2022-10-03 21:56 UTC
Labels: User Story
