### ISSUE TITLE
Silver or gold cluster

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#181] opened 2022-04-01 15:41 UTC
As a stakeholder
I would like to decide on which cluster to use
so that we can know where to deploy our application

**Comment by elliottSlee** [comment] 2022-06-02 18:47
@BryanGK close this?

**Comment by MarsRomer** [comment] 2022-06-14 21:59
@BryanGK  do we still need this ticket?

**Comment by BryanGK** [comment] 2022-06-14 22:18
@MarsRomer @elliottSlee I remember us discussing whether there would be a move to the gold cluster or not. Mars if you consider the matter resolved, then yes close the ticket.

**Comment by MarsRomer** [comment] 2022-06-14 22:21
@BryanGK thanks for the reminder, I understand now what this ticket is about.  I think at some point it might be worth moving to the gold cluster so I will put this in the product backlog for now

**Comment by elliottSlee** [comment] 2022-09-13 20:49
@MarsRomer I'm guessing this can be closed?

**Comment by MarsRomer** [comment] 2022-09-13 21:06
not quite
we may be moving to gold on OpenShift, we haven't done it yet.  Possibly a duplicate ticket though

**Comment by elliottSlee** [comment] 2022-11-03 14:01
@marcellmueller is this a duplicate of #296?

**Closed** 2022-12-12 16:59 UTC
Labels: help wanted
