### ISSUE TITLE
Mock time for Happo screenshots

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#495] opened 2022-08-25 14:03 UTC
Currently our Happo diffs fail every time since the time is different in every screenshot when saving. We need to fix that so that approving these false positives doesn't let something else slip through.

**Comment by matthieu-foucault** [comment] 2022-08-26 15:57
Duplicate of #485

**Closed** 2022-08-26 15:57 UTC
Labels: duplicate
