### ISSUE TITLE
Side Navigation 

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#122] opened 2022-05-10 16:49 UTC
**As a** [type of user or profile] (who performs the action?)
**I want** [action] (what they are doing?)
**so that** [reason behind goal] (why this is important? What problem is this solving?)

### Description: 

_(Brief description of the work involved, including any user research context or key decisions.)_

### Acceptance Criteria:

- [ ] Task
- [ ] Task
- [ ] Task

**Comment by elliottSlee** [comment] 2022-05-10 18:53
duplicate of #119

**Closed by elliottSlee** 2022-05-10 18:53 UTC
Labels: feature
