### ISSUE TITLE
Error logging in export attachment function

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#1021] opened 2022-12-15 23:27 UTC
As an analyst
I want to see any errors created in the Export Attachments feature, if they are to occur, in a text file
So that I can ask the devs to fix the problems

## Acceptance Criteria:

- [x] **Scenario: Error message structure**
Errors detected - please send this file to meherzad.romer@gov.bc.ca
[Todays timestamp]

These files were not included in the downloaded zip file due to errors:
[Error number] - [filename on S3] - [file name in db] - [filetype] - [size on S3] - [size according to database] - [CCBC-ID] - [upload date and time]  - [Error timestamp]
Error Details:
[error messages for developers to decipher]

[Error number] - [filename on S3] - [file name in db] - [filetype] - [size on S3] - [size according to database] - [CCBC-ID] - [upload date and time]  - [Error timestamp]
Error Details:
[error messages for developers to decipher]

[Error number] - [filename on S3] - [file name in db] - [filetype] - [size on S3] - [size according to database] - [CCBC-ID] - [upload date and time]  - [Error timestamp]
Error Details:
[error messages for developers to decipher]

- [x] if no errors found then text file says 'Download successfull'
.
.
.
#
- [x] **Error code definition**
     The error code maps to an enumerator in our control system.
#
- [x] **Scenario: Capture the errors in the Export Attachments feature**
    Given there are one or more errors in the Export Attachments feature
    When I try to export 
    Then each error captured will be saved 
    And these errors will be saved in the `errors.txt` with the logs
#
- [x] **Scenario: Add the error log file to the ZIP file**
    Given I try to Export Attachments on the Dashboard
    When an error occurs in one or more files
    Then an `errors.txt` file that includes a list of filenames and their respective errors description is added to the ZIP file.

## Not included:
-
-

## Ultra refinement
DB:
- no updates in the database.

Middleware:
- [x]  Map the error code in the JSON

Frontend:
- no updates in the front end. 

Integration/API:
- no integration.

Tests:
- [x] yes, ...

Documentation:
- [x] Create the Error code definition.

**Comment by AntBush** [comment] 2022-12-19 18:24
The errors.txt I think will be moreso for the devs, so that if one exists it can be given to the developers/us to look into.

**Comment by MarsRomer2** [comment] 2022-12-19 19:14
@marcellmueller @AntBush @VB-at-Bis @pdoc1111 please add a list of the errors that we do know we may get to this ticket so that I can add the desired wording

**Comment by marcellmueller** [comment] 2023-01-16 22:38
Putting a blocked label on this as we can't realistically start on it until #1043 is completed which will involve a refactor and moving it to AWS Lambda.

**Comment by VB-at-Bis** [comment] 2023-02-03 17:01
The ticket should be tested in test or prod environment because dev env does not have applications with attachments and generated Intake_1 ..json is empty.

Steps to reproduce after deployment: 
1. delete Intake_1 .. json and zip files from S3;
2. run `https://test.connectingcommunitiesbc.ca/api/analyst/admin-archive/1` in Postman with header `x-api-key` set to S3 secret key;
3. locate file Intake_1 .. json in S3 bucket, download it locally and verify that list of attachments contain file types and sizes;
4. locate file Intake_1 .. zip in S3 bucket, download it locally and verify that error.txt has single line with 'Download successful' text;
5. choose any file from the list, save it as backup copy, note it's size and file type, then create new file with different size and upload it manually to S3 with the same key (overwrite real attachment);
6. repeat steps 1 and 2;
7. locate file Intake_1 .. zip in S3 bucket, download it locally and verify that error.txt contains expected error regarding size mismatch;
8. upload original file to S3 with same key (restore attachment)
9. choose any file from the list, save it as backup copy, note it's size and file type, then create new file with different file type and upload it manually to S3 with the same key (overwrite real attachment); 
10. repeat steps 1 and 2;
11. locate file Intake_1 .. zip in S3 bucket, download it locally and verify that error.txt contains expected error regarding file type mismatch;
12. repeat step 8;
13. choose any file from the list, locate object in S3 bucket and change tag `av_status` to `dirty`;
14. repeat steps 1 and 2;
15. locate file Intake_1 .. zip in S3 bucket, download it locally and verify that error.txt contains expected error regarding infected file;
16. repeat steps 8, 1 and 2 to ensure valid intake archive to be stored in S3;

**Comment by eazeredo** [comment] 2023-02-09 18:55
@MarsRomer @MarsRomer-zz, we can provide a demo if you wish. Otherwise, let's close this card.

**Comment by VB-at-Bis** [comment] 2023-02-14 02:04
[https://app.zenhub.com/files/476885245/f32723c7-391a-40f5-ab69-caecdb63bba9/download](https://app.zenhub.com/files/476885245/f32723c7-391a-40f5-ab69-caecdb63bba9/download)
Attached `error.txt` file.

**Closed** 2023-02-18 00:04 UTC
Labels: Task
