### ISSUE TITLE
Bug: Error message upon Submit

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#374] opened 2022-08-03 20:24 UTC
When I filled out the form and hit submit it gave me this error screen:
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/84a48d4b-fed9-4ffe-95e1-438d94997d78)

Refreshing the browser does not help, I still get the same message and when I go to the dashboard, my application is still showing as Draft instead of Submitted.

**Matthieu's update:**
- The bug will be intermittent: the application doesn't wait for the CCBC Id and intake number to be assigned before navigating to the success page. Whether or not the bug happens depends on your browser and your network's speed

**Comment by eazeredo** [comment] 2022-08-05 16:39
@marcellmueller To reproduce the error on the Test environment, create a new application, go to the last page, and submit.

The error will show up, and the application status is changed to Submitted.

**Comment by MarsRomer** [comment] 2022-08-05 16:47
@eazeredo  were you able to reproduce the error with these steps?

**Comment by eazeredo** [comment] 2022-08-05 22:08
@Mars Yes, I reproduce the error with that steps. But I'm trying again, and it didn't happen again. Happened only once.

**Comment by mars** [comment] 2022-08-05 22:11
Wrong Mars @eazeredo 🙏

**Comment by MarsRomer** [comment] 2022-08-09 04:40
Yes it happened to me again today.

**Comment by matthieu-foucault** [comment] 2022-08-09 15:25
@MarsRomer , @eazeredo I can't reproduce the issue, would you be able to provide some error logs from the browser console?

**Comment by MarsRomer** [comment] 2022-08-11 03:59
Happened again, here's the screenshot with the debugger
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/6537bdbd-8ae8-4165-a486-6276f11cbcdf)

**Comment by MarsRomer** [comment] 2022-08-11 23:39
@matthieu-foucault did I hear you say you fixed this problem? if so can we please get it into test for tomorrows demo?

**Comment by matthieu-foucault** [comment] 2022-08-12 15:20
The cause of the problem was identified. It still needs a fix and a test

**Comment by MarsRomer** [comment] 2022-08-12 15:25
interestingly it's working for me now

**Comment by matthieu-foucault** [comment] 2022-08-12 15:27
The bug will be intermittent: the application doesn't wait for the CCBC Id and intake number to be assigned before navigating to the success page. Whether or not the bug happens depends on your browser and your network's speed

**Comment by MarsRomer** [comment] 2022-08-17 22:40
can we do something so that this doesn't happen? my network speed is pretty good most times and I'm mostly using chrome

**Closed** 2022-08-24 20:32 UTC
Labels: bug, inSprint
