### ISSUE TITLE
Review PR template

### ISSUE THREAD

**Issue by eazeredo** [bcgov/CONN-CCBC-portal#441] opened 2022-08-17 15:51 UTC
I am opening this thread to start the conversation about how we can improve and making really useful the PR template as part of our continuous improvement process. I'm focusing now on the PR, and after that, we can talk about the DoD for the card/issue.
 
**The problem (why)**
Today, what we have is not working. It's toil. The team composition changed a couple of times since the current PR template was written, and it's not seeing benefits in following it.
A template should be helpful for the team as a reminder of the team's agreements.

**The ask (what)**
Each one individually identifies what items on the PR template are not working and what is missing.

Name someone in the team to consolidate the individual list to be discussed together.

**The output (still what)**
A simple list of items of your choice that MUST be checked before submitting a PR for review.
 
**The final goal**
Empower and give ownership to each team member to help as much as possible the team to accomplish the work.

**Comment by AntBush** [comment] 2022-08-17 16:04
I think the only parts that are required are just about this, specifically with the DoD since many of the rest are implicit (code added and reviewed shouldn't be breaking, defective, etc) and should be detected with SonarCloud/Tests 

### Description: 

_(Brief description of the pull request.)_

References # \<issue number\>

### Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update


### Checklist for DoD:
- [ ] Tests written and passing (e2e, db, and/or unit where applicable)
- [ ] All acceptance criteria met
- [ ] Peer Reviewed

**Comment by eazeredo** [comment] 2022-08-25 15:36
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/441?planning-poker) with Zenhub @AntBush @marcellmueller @matthieu-foucault @wenzowski

**Comment by wenzowski** [comment] 2022-08-25 17:26
Can we enforce Peer Review? Maybe even by identifying codeowners? Then it becomes a part of our required status checks rather than checklist. I’d love to lean into getting as many of these checks for DoD into required status checks as possible (eliminate toil)

**Comment by VB-at-Bis** [comment] 2022-09-15 16:02
Suggestion for `Checklist for DoD`: 
if type of change is new feature or breaking change then test coverage should not decrease 
- [ ] Test code coverage is not decreasing (where applicable)

**Comment by matthieu-foucault** [comment] 2022-09-15 16:07
Suggestion for` Checklist for DoD`:

How are the changes tested?
- [ ] Database unit tests
- [ ] Jest tests
- [ ] Cypress tests
- [ ] Manual testing (indicate steps to reproduce testing): 
- [ ] Other (please specify): 
- [ ] No tests (please indicate why this should be merged anyway)

**Closed** 2022-10-05 20:36 UTC
Labels: inSprint, High Priority ⚠️
